// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyStoreAPI.Data;

#nullable disable

namespace SkyStoreAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241227140247_fixTable")]
    partial class fixTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyStoreAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sandal Items",
                            Name = "Sandal"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Clothing Items",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Shoe Items",
                            Name = "Shoe"
                        });
                });

            modelBuilder.Entity("SkyStoreAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "",
                            Name = "Giay Sneaker",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "",
                            Name = "Ao Hoodie",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "",
                            ImageUrl = "",
                            Name = "Giay Nice",
                            Price = 100.0
                        });
                });

            modelBuilder.Entity("SkyStoreAPI.Models.Product", b =>
                {
                    b.HasOne("SkyStoreAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
